# Generated by Django 4.0.1 on 2022-02-16 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registered_courses',
        ),
    ]
