# Generated by Django 3.0.8 on 2020-08-09 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='coursess',
            new_name='coursesscat',
        ),
    ]
