# Generated by Django 4.0.1 on 2022-02-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_user_registered_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registered_courses',
            field=models.ManyToManyField(to='school.Course_Description'),
        ),
    ]
