# Generated by Django 4.0.1 on 2022-02-17 16:08

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import school.models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_user_registered_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('texts', ckeditor_uploader.fields.RichTextUploadingField()),
                ('premium', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='select_course',
            name='users',
        ),
        migrations.RemoveField(
            model_name='course_description',
            name='course_category',
        ),
        migrations.RemoveField(
            model_name='course_description',
            name='course_name',
        ),
        migrations.AddField(
            model_name='course_description',
            name='image',
            field=models.ImageField(default='default_profile.jpg', upload_to='courses/images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png', 'jpg']), school.models.valid_image_mimetype, school.models.valid_size]),
        ),
        migrations.DeleteModel(
            name='Course_category',
        ),
        migrations.DeleteModel(
            name='Select_course',
        ),
        migrations.AddField(
            model_name='topics',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='school.course_description'),
        ),
    ]
