# Generated by Django 4.0.1 on 2022-02-17 16:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_topics_remove_select_course_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='instagram',
        ),
        migrations.AddField(
            model_name='tutor',
            name='about',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='course_description',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.RemoveField(
            model_name='course_description',
            name='tutor',
        ),
        migrations.AddField(
            model_name='course_description',
            name='tutor',
            field=models.ManyToManyField(to='school.Tutor'),
        ),
    ]
