# Generated by Django 4.0.1 on 2022-02-19 12:34

import django.core.validators
from django.db import migrations, models
import school.models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_remove_tutor_image_remove_tutor_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='image',
            field=models.ImageField(default='default_profile.jpg', upload_to='courses/images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'png', 'jpg']), school.models.valid_image_mimetype, school.models.valid_size]),
        ),
    ]
