# Generated by Django 2.2.15 on 2020-08-16 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangorave', '0002_auto_20190815_0524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttypemodel',
            options={'verbose_name': 'Payment Type'},
        ),
        migrations.AlterModelOptions(
            name='transactionmodel',
            options={'verbose_name': 'Transaction'},
        ),
    ]
