# Generated by Django 3.1 on 2020-08-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangorave', '0003_auto_20200816_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttypemodel',
            name='expiry',
            field=models.IntegerField(choices=[(30, 'Monthly'), (120, 'Quaterly'), (365, 'Yearly')], default=30),
        ),
    ]
