# Generated by Django 3.1 on 2020-08-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangorave', '0004_paymenttypemodel_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttypemodel',
            name='expiry',
            field=models.IntegerField(choices=[(30, 'Month'), (120, 'Quater'), (365, 'Year')], default=30),
        ),
    ]
