from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("", views.home , name="home"),
    path("prem", views.prem , name="prem"),
    path('about', views.about, name='about'),
    path('join/<int:course_page>', views.join, name='join'),
    path('register', views.register, name='register'),
    path("index", views.index, name='index'),
    path("login", views.loginv, name="login"),
    path("gallary", views.gallary, name='gallary'),
    path("contact",views.contact,name='contact'),
    path('register', views.register, name='register'),
    path("courses",views.courses,name='courses'),
    # path("upload", views.upload_book , name='upload'),
    path("join_course", views.join_course , name='join_course'),
    # path("download", views.download, name='download'),
    # path("<int:book_id>", views.about_books, name='about_books'),
    path("logout", views.logout_request , name='logout'),
    path("profile/<int:id>", views.profile_view, name='profile'),
    # path("edit",views.update_pofile, name = 'edit'),
    # path('ratings', include('star_ratings.urls', namespace='ratings'), name='ratings'),
    # path("author",views.reg_author, name = 'author'),
    path("run/",views.compiler, name = 'run'),
#    path('<int:downloadfile>/', views.download_file , name='file'),
    path("display",views.display_course, name = 'display'),
    path("tutname",views.tut, name = 'tutname'),
    path("tut",views.tutorial, name = 'tut'),
    # path("genre/<int:id>",views.genre_func, name = 'genre'),
    path("feedback",views.mail, name = 'feedback'),
    path("premium/<int:course_page>",views.premium, name = 'premium'),
    path('accounts/', include('allauth.urls')),
    path("djangorave/", include("djangorave.urls", namespace="djangorave")),
#    path("newsletter/", include("newsletter.urls")),
    path('pay', views.payment, name='pay'),
    path('reset_password/',auth_views.PasswordResetView.as_view(template_name='school/password_reset.html'), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='school/password_reset_sent.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='school/password_reset_form.html'), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='school/password_reset_done.html'), name='password_reset_complete'),
    # path('create', views.createnovella, name='create'),
    # path('story/<int:book>',views.editnovella, name='editnovella'),
    # path('read/<slug:book>',views.novella, name='read'),
    # path('details/<str:story>/<int:book>', views.details, name='details'),
    path('payment/<str:reference>/<int:amount>', views.callback, name='payment'),
    # path('premiumstories/<slug:book>' ,views.premiumstories , name="premiumstories"),
    path('cancel', views.cancelSubscription, name='cancel'),
    path('user_profile', views.profile , name='user_profile'),
    # path('editnovella/<int:book>', views.editnovella, name='editnovella'),
    path('quiz/<int:topic>', views.quiz_score, name='quiz'),
    path('quiz/<int:topic>/<int:question>', views.question, name='question'),
    path('createquiz', views.create_quiz, name='createquiz'),
    path('all_questions', views.display_questions, name='all_questions'),
    path('edit_question/<int:num>/<str:edit_or_del>', views.edit_quiz, name='edit_quest'),


]